services:
  front:
    image: ghcr.io/mathador/p9_microcrm_front:main
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - back
    networks:
      - microcrm-network

  back:
    image: ghcr.io/mathador/p9_microcrm_back:main
    ports:
      - "8080:8080"
    networks:
      - microcrm-network

networks:
  microcrm-network:
    driver: bridge
