services:
  front:
    image: ghcr.io/mathador/p9_microcrm_front:main
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
        tag: "microcrm-front"
    depends_on:
      - back
      - logstash
    networks:
      - microcrm-network

  back:
    image: ghcr.io/mathador/p9_microcrm_back:main
    ports:
      - "8080:8080"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
        tag: "microcrm-back"
    depends_on:
      - logstash
    networks:
      - microcrm-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - microcrm-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.3
    ports:
      - "12201:12201/udp"
      - "9600:9600"
    depends_on:
      - elasticsearch
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./observability/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    networks:
      - microcrm-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - microcrm-network

networks:
  microcrm-network:
    driver: bridge

volumes:
  elasticsearch-data:
