input {
  gelf {
    port => 12201
  }
}

filter {
  if [container_name] {
    mutate {
      add_field => { "service_name" => "%{container_name}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "microcrm-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
